spring:
  datasource:
    url : jdbc:postgresql://localhost:5433/Blog
    username: postgres
    password: Crash_bandicoot2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true